[package]
name = "rust-firebase-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "*"
firebase-rs = "*"
serde = "*"
tokio = { version = "*", features = ["full"] }
